---
title: "test"
output: html_document
---

## Including Plots

You can also embed plots, for example:
```{r}
library(tidyverse)
```
```{r pressure, echo=FALSE}
country_data <- read_excel("mapData.xlsx")
country_data <- filter(country_data, Top_Category != "NA")
 robot <- image_read("RobotImage.png") %>%
    image_trim()
 money <- image_read("MoneyBag.png") %>%
    image_trim()%>%
    image_fill("none", point = "+0+0", fuzz = 0) %>%
    image_fill("none", point = "+300+0", fuzz = 0) %>%
    image_fill("none", point = "+0+300", fuzz = 0) %>%
    image_fill("none", point = "+390+300", fuzz = 0) %>%
    image_scale("50x50")
img = image_composite(robot, money,gravity = "south", offset = "+120+0")
print(img)
```

```{r}
# Cases and Deaths information based on country_data of one country

casesPerMillion <- as.numeric(country_data[country_data$Country == "Spain","Covid_Cases_Per_Million"][[1]])
deathsPerMillion <- as.numeric(country_data[country_data$Country == "Spain","Covid_Deaths_Per_Million"][[1]])
casesQuantile <- unname(quantile(as.numeric(country_data$Covid_Cases_Per_Million), na.rm = TRUE))
deathsQuantile <- unname(quantile(as.numeric(country_data$Covid_Deaths_Per_Million), na.rm = TRUE))
```

```{r}
#Ggplot of CovidDeaths only

ggplot(country_data) + 
  geom_boxplot(aes(y=as.numeric(Covid_Deaths_Per_Million))) + 
  scale_x_discrete() + 
  labs(title = "Covid Deaths per Million for All Countries", y = "Covid Deaths (Per Million)", x = "Countries Quartile Information") + 
  coord_flip() + 
  geom_point(data = single_data, aes(y = as.numeric(Covid_Deaths_Per_Million), x = 0), colour = "blue", size = 4) +
  geom_text(data = single_data, aes(y = as.numeric(Covid_Deaths_Per_Million), x = 0, label = paste(Country, ":",Covid_Deaths_Per_Million) , vjust =-1.5, family = "serif"), fontface = "bold") + theme_classic()
```

```{r}
#Draw cases on mask
 if(casesPerMillion <= casesQuantile[2]){#first quartile
      robot1 <- image_fill(robot, "lightcyan", point = "+455+180", fuzz = 0)
 }else if(casesPerMillion <= casesQuantile[3]){#second quartile
      robot1 <- image_fill(robot, "lightblue2", point = "+455+180", fuzz = 0)
 }else if(casesPerMillion <= casesQuantile[4]){#third
     robot1 <- image_fill(robot, "lightskyblue", point = "+455+180", fuzz = 0)
 }else if(casesPerMillion <= casesQuantile[5]){#fourth
      robot1 <- image_fill(robot, "dodgerblue4", point = "+455+180", fuzz = 0)
 }
print(robot1)
```

```{r}
# Draw deaths on cross

 if(deathsPerMillion <= deathsQuantile[2]){#first quartile
      robot1 <- image_fill(robot, "lightpink", point = "+250+30", fuzz = 0)
 }else if(deathsPerMillion <= deathsQuantile[3]){#second quartile
      robot1 <- image_fill(robot, "brown1", point = "+250+30", fuzz = 0)
 }else if(deathsPerMillion <= deathsQuantile[4]){#third
      robot1 <- image_fill(robot, "lightpink", point = "+250+30", fuzz = 0)
 }else if(deathsPerMillion <= deathsQuantile[5]){#fourth
      robot1 <- image_fill(robot, "red4", point = "+250+30", fuzz = 0)
 }

print(robot1)
#Needle
##EYES: +200+110 +255+120
##Mask +455+180
```

```{r}
money <- image_read("flags/Australia.jpg") %>%
  image_trim() %>%
    image_scale("50x50")

img <- image_composite(robot, money, offset = "+150+250")
print(img)
```
